In [1]:
import pandas as pd
from datetime import datetime

### Read all files

In [2]:
path1 = r"Z:\Groups\TMG\Research\2022\CAF\ModeImputationModel\Bogota GPS Final\Transit-Fixed.csv"
bogota_GPS = pd.read_csv(path1)
bogota_GPS

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,TripDuration,Weekend,Weekday,RoadTime,RoadDistance,duration (min),walkTime (min),transitTime (min),waitingTime (min),transfers
0,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.625118,-74.125770,4.587117,-74.100170,383,501,08:08:11,15:57:24,0,1,7.820278,6.547610,8.422235,28.933333,8.933333,19.966667,0.033333,0
1,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.587117,-74.100170,4.588438,-74.100660,501,501,12:39:56,12:59:55,0,1,0.333056,0.440450,0.641031,2.716667,2.716667,0.000000,0.000000,0
2,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.588438,-74.100660,4.624916,-74.125450,501,383,13:20:20,20:31:11,0,1,7.180833,5.652214,7.139969,25.400000,5.933333,19.433333,0.033333,0
3,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.624916,-74.125450,4.586052,-74.098510,383,501,20:51:21,10:30:43,0,1,13.656111,5.630680,7.536019,32.500000,12.500000,19.966667,0.033333,0
4,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.586052,-74.098510,4.624972,-74.125560,501,383,14:45:27,00:28:40,0,1,9.720278,6.405847,7.860111,28.100000,8.633333,19.433333,0.033333,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13143439,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.700045,-74.101310,4.698133,-74.097560,184,184,12:30:32,12:41:54,0,1,0.189444,0.431090,0.616997,6.950000,6.950000,0.000000,0.000000,0
13143440,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.698133,-74.097560,4.699910,-74.101550,184,184,13:21:21,13:56:34,0,1,0.586944,0.408952,0.613428,7.633333,7.633333,0.000000,0.000000,0
13143441,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699910,-74.101550,4.695521,-74.104660,184,183,15:46:14,16:29:24,0,1,0.719444,1.120152,1.361477,10.933333,10.933333,0.000000,0.000000,0
13143442,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.695521,-74.104660,4.699883,-74.101456,183,184,20:09:11,20:31:57,0,1,0.379444,0.961919,1.078776,5.216667,3.433333,1.750000,0.033333,0
13143443,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699883,-74.101456,4.695547,-74.104680,184,183,20:58:47,21:22:29,0,1,0.395000,1.113022,1.350782,11.066667,11.066667,0.000000,0.000000,0

In [3]:
bogota_GPS.describe()

,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripDuration,Weekend,Weekday,RoadTime,RoadDistance,duration (min),walkTime (min),transitTime (min),waitingTime (min),transfers
count,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07,1.314344e+07
mean,4.667367e+00,-7.411373e+01,4.667415e+00,-7.411364e+01,5.190188e+02,5.188550e+02,2.591218e-01,7.408782e-01,7.739226e+00,7.342960e+00,8.182172e+00,2.628228e+01,7.020252e+00,1.557687e+01,3.685155e+00,1.618792e-01
std,9.495587e-02,6.886790e-02,9.492693e-02,6.885451e-02,3.952769e+02,3.952812e+02,4.381526e-01,4.381526e-01,2.985697e+01,9.104684e+00,9.691531e+00,2.803292e+01,5.443683e+00,2.064507e+01,7.388558e+00,7.227684e-01
min,3.826154e+00,-7.455341e+01,3.826154e+00,-7.455341e+01,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,-2.853500e+01,-1.000000e+00,-1.000000e+00,-6.000000e+00,-2.000000e+00,-2.000000e+00,-2.000000e+00,-2.000000e+00
25%,4.605329e+00,-7.414809e+01,4.605407e+00,-7.414794e+01,2.160000e+02,2.170000e+02,0.000000e+00,0.000000e+00,3.561111e-01,7.781980e-01,9.589113e-01,4.233333e+00,3.516667e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,4.651102e+00,-7.410670e+01,4.651190e+00,-7.410661e+01,4.360000e+02,4.350000e+02,0.000000e+00,1.000000e+00,1.142500e+00,3.938319e+00,4.480795e+00,1.540000e+01,6.666667e+00,4.783333e+00,3.333333e-02,0.000000e+00
75%,4.712571e+00,-7.407006e+01,4.712486e+00,-7.406998e+01,7.520000e+02,7.520000e+02,1.000000e+00,1.000000e+00,3.891389e+00,1.145744e+01,1.285161e+01,4.576667e+01,1.008333e+01,2.796667e+01,1.033333e+01,1.000000e+00
max,5.288288e+00,-7.369621e+01,5.288288e+00,-7.369621e+01,1.908000e+03,1.908000e+03,1.000000e+00,1.000000e+00,7.164778e+02,2.387621e+02,2.330002e+02,8.627667e+02,9.616667e+01,4.875833e+02,7.441167e+02,4.000000e+00

In [4]:
bogota_GPS['duration (min)'].sort_values().value_counts()

-3.000000      1575835
-6.000000       183567
 2.783333         9661
 3.016667         9604
 2.800000         9593
                ...
 167.433333          1
 167.450000          1
 167.500000          1
 167.566667          1
 862.766667          1
Name: duration (min), Length: 20506, dtype: int64

In [5]:
bogota_GPS = bogota_GPS.rename(columns={'TripDuration':'Weekend',
                                        'Weekend':'Weekday',
                                        'Weekday':'TripDuration'})

In [6]:
path2 = r"Z:\Groups\TMG\Research\2022\CAF\ModeImputationModel\Bogota GPS Final\Number of transit stops in each TAZ.csv"
num_transit_stops = pd.read_csv(path2)
num_transit_stops

,ZAT,Area (sq. m),Total number of transit stops,Number of Troncal stops,Number of Alimentadores stops,Number of Complementaria stops,Number of Especial stops,Total length of transit routes (m)
0,1,3.271071e+06,0,0,0,0,0,204.759390
1,2,2.246763e+06,0,0,0,0,0,0.000000
2,3,1.113507e+06,2,2,0,0,0,1334.133793
3,4,9.537258e+05,2,2,0,0,0,7508.219929
4,5,3.326493e+05,0,0,0,0,0,0.000000
...,...,...,...,...,...,...,...,...
1136,1904,4.006448e+07,0,0,0,0,0,0.000000
1137,1905,7.127136e+07,0,0,0,0,0,0.000000
1138,1906,1.782966e+08,0,0,0,0,0,0.000000
1139,1907,1.782966e+08,0,0,0,0,0,0.000000
1140,1908,5.530580e+07,0,0,0,0,0,0.000000

In [7]:
path3 = r"Z:\Groups\TMG\Research\2022\CAF\ModeImputationModel\Bogota GPS Final\HomeZone-ExcludeOutsidePings-Bogota.csv"
home_zone = pd.read_csv(path3)
home_zone

,DeviceId,Lat,Lon,Taz,Stays,Clusters
0,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,-1.000000,-1.000000,-1,6,0
1,a200YnR0ZWl1M29uOjEydmVxMGkzdG4xMzY=,-1.000000,-1.000000,-1,5,0
2,a200ZjB2cXI0aTdlOjVzcDFhbm0xNHR2OXM=,-1.000000,-1.000000,-1,1,0
3,a201cTRqaWs4M2VxOjVxM2Q2bzVzZm8xMHY=,-1.000000,-1.000000,-1,1,0
4,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,-74.108389,4.742909,114,36,1
...,...,...,...,...,...,...
1809361,ZzZzM3BvaGRsdTEwOjllcGRhZ2Qwb2tnMzU=,-1.000000,-1.000000,-1,1,0
1809362,ZzZzMTBjMnVvajVkOjU3NTd1MjBxbzRqbm0=,-1.000000,-1.000000,-1,1,0
1809363,ZzZzMWtrYTNvcDk5OjYzZHVsZGJvZTBrYm4=,-1.000000,-1.000000,-1,1,0
1809364,ZzZzZDZhZ3BhOGx1OmQ2czJ1bjVvMmZ1ODI=,-74.162363,4.601620,543,21,1
1809365,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,-74.102954,4.697967,183,41,1

In [8]:
path4 = r"Z:\Groups\TMG\Research\2022\CAF\ModeImputationModel\Bogota GPS Final\Bogota_devices_with_home_and_SEindicator.csv"
socio_demo = pd.read_csv(path4)
socio_demo

,DeviceId,Lon,Lat,Stays,Clusters,hex_o,Poblacion,area_m2,NSE,NSE3
0,NTZzaHUxcDNjcmV1ZDozOG5nZ21ncTgxZjBt,-74.183817,4.566663,27,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo
1,NW5zbjMwaDV0N2puMjphbWpsazdpODZ1NnAy,-74.177602,4.571539,29,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo
2,NTE4aGNlcms3ZHB0djpkajhrdWNzMDE2ZDA5,-74.181735,4.573120,37,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo
3,NTMwajU5aG9pa3BhbjpkdmdiNm9jOWNydHNy,-74.183087,4.567099,13,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo
4,NXBsczdpZ2dpbWVpOTpiN3ZhcGVrY3F1bmtv,-74.180045,4.570669,25,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo
...,...,...,...,...,...,...,...,...,...,...
286639,ZnRucXZiNzdtbnI5bTo4MjlpcXJvZ3YzNGJ2,-74.155588,4.587725,42,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio
286640,ZTljMWFkMzZpamVzajplYjF2c2Q5dnRmN2Vs,-74.155067,4.586321,49,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio
286641,ZTM4M3NmNjlhMnUydTpkZ2JnYWNmdG0xc3Rj,-74.160132,4.585009,11,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio
286642,ZTdoMjYzMWswaXUyODo2MXJoYTdhdnE2c2tn,-74.153778,4.587746,15,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio
286643,ZTk1Z2NzNW8zaHBoYTplMmNmNDdtN3Rla3Jh,-74.157386,4.582126,34,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio

In [9]:
path5 = r'Z:\Groups\TMG\Research\2022\CAF\ModeImputationModel\Bogota GPS Final\BGTA_Attributes_TAZ_ToGPS_O.csv'
bgt_TAZ_O = pd.read_csv(path5)
bgt_TAZ_O

,ZAT_O,Population_O,Area_km2_O,PopPerKM2,Agro2018_perZAT_O,Com2018_perZAT_O,Ind2018_perZAT_O,Serv2018_perZAT_O,Other2018_perZAT_O,Agro2018_perZAT_perKM2_O,Com2018_perZAT_perKM2_O,Ind2018_perZAT_perKM2_O,Serv2018_perZAT_perKM2_O,Other2018_perZAT_perKM2_O
0,1,0.0,3.2711,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1,2,0.0,2.2468,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
2,3,0.0,1.1135,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
3,4,0.0,0.9537,0.0,0.364,3.364,2.273,9.000,0.545,0.381,3.527,2.383,9.437,0.572
4,5,0.0,0.3326,0.0,0.800,17.800,5.933,10.933,1.000,2.405,53.510,17.837,32.867,3.006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136,1904,0.0,40.0645,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1137,1905,0.0,71.2714,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1138,1906,0.0,178.2966,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1139,1907,0.0,178.2966,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1140,1908,0.0,55.3058,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000

In [10]:
path6 = r'Z:\Groups\TMG\Research\2022\CAF\ModeImputationModel\Bogota GPS Final\BGTA_Attributes_TAZ_ToGPS_D.csv'
bgt_TAZ_D = pd.read_csv(path6)
bgt_TAZ_D

,ZAT_D,Population_D,Area_km2_D,PopPerKM2_D,Agro2018_perZAT_D,Com2018_perZAT_D,Ind2018_perZAT_D,Serv2018_perZAT_D,Other2018_perZAT_D,Agro2018_perZAT_perKM2_D,Com2018_perZAT_perKM2_D,Ind2018_perZAT_perKM2_D,Serv2018_perZAT_perKM2_D,Other2018_perZAT_perKM2_D
0,1,0.0,3.2711,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1,2,0.0,2.2468,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
2,3,0.0,1.1135,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
3,4,0.0,0.9537,0.0,0.364,3.364,2.273,9.000,0.545,0.381,3.527,2.383,9.437,0.572
4,5,0.0,0.3326,0.0,0.800,17.800,5.933,10.933,1.000,2.405,53.510,17.837,32.867,3.006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136,1904,0.0,40.0645,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1137,1905,0.0,71.2714,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1138,1906,0.0,178.2966,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1139,1907,0.0,178.2966,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000
1140,1908,0.0,55.3058,0.0,NaN,NaN,NaN,NaN,NaN,-1.000,-1.000,-1.000,-1.000,-1.000

### Merge datasets to each other

In [11]:
home_zone.columns

Index(['DeviceId', 'Lat', 'Lon', 'Taz', 'Stays', 'Clusters'], dtype='object')

In [12]:
home_zone = home_zone.drop('Clusters', axis=1)

In [13]:
home_zone = home_zone.rename(columns={'Lat': 'Lat_home', 'Lon': 'Lon_home', 'Taz':'Taz_home' })

In [14]:
home_zone_true = home_zone[home_zone['Taz_home'] != -1]

In [15]:
100* len(home_zone_true)/len(home_zone)

16.948754425583324

In [16]:
home_zone_true

,DeviceId,Lat_home,Lon_home,Taz_home,Stays
4,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,-74.108389,4.742909,114,36
7,a201YWxhamRhajQxOjNraDkxdXVmNjNkbTI=,-74.180503,4.603353,544,58
9,a202bDNrN2M5N3UwOjI0N3Y1YnBpODZxb2U=,-74.115785,4.645940,325,56
12,a203dGNoMXBvOGEwOmVsZm02MGN1M2xtNDI=,-74.122449,4.616962,382,13
16,a204MXRqZnN2MHN1OjcxcWE5ajVpNWxyZjU=,-74.117623,4.539592,703,14
...,...,...,...,...,...
1809354,ZzZwYjEzcGFwZnFnOmNxaG11MjhiNHI1a3E=,-74.105881,4.740089,114,29
1809355,ZzZwYm1tMHNmbDdrOjY0NWIycTB1bWs4cHU=,-74.148294,4.582117,620,79
1809359,ZzZyN2ZmbzNqcXVjOjQxMjFtaXVocmtsOGg=,-74.093503,4.531732,693,15
1809364,ZzZzZDZhZ3BhOGx1OmQ2czJ1bjVvMmZ1ODI=,-74.162363,4.601620,543,21
1809365,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,-74.102954,4.697967,183,41

In [17]:
bogota_GPS

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,Weekend,Weekday,TripDuration,RoadTime,RoadDistance,duration (min),walkTime (min),transitTime (min),waitingTime (min),transfers
0,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.625118,-74.125770,4.587117,-74.100170,383,501,08:08:11,15:57:24,0,1,7.820278,6.547610,8.422235,28.933333,8.933333,19.966667,0.033333,0
1,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.587117,-74.100170,4.588438,-74.100660,501,501,12:39:56,12:59:55,0,1,0.333056,0.440450,0.641031,2.716667,2.716667,0.000000,0.000000,0
2,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.588438,-74.100660,4.624916,-74.125450,501,383,13:20:20,20:31:11,0,1,7.180833,5.652214,7.139969,25.400000,5.933333,19.433333,0.033333,0
3,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.624916,-74.125450,4.586052,-74.098510,383,501,20:51:21,10:30:43,0,1,13.656111,5.630680,7.536019,32.500000,12.500000,19.966667,0.033333,0
4,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.586052,-74.098510,4.624972,-74.125560,501,383,14:45:27,00:28:40,0,1,9.720278,6.405847,7.860111,28.100000,8.633333,19.433333,0.033333,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13143439,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.700045,-74.101310,4.698133,-74.097560,184,184,12:30:32,12:41:54,0,1,0.189444,0.431090,0.616997,6.950000,6.950000,0.000000,0.000000,0
13143440,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.698133,-74.097560,4.699910,-74.101550,184,184,13:21:21,13:56:34,0,1,0.586944,0.408952,0.613428,7.633333,7.633333,0.000000,0.000000,0
13143441,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699910,-74.101550,4.695521,-74.104660,184,183,15:46:14,16:29:24,0,1,0.719444,1.120152,1.361477,10.933333,10.933333,0.000000,0.000000,0
13143442,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.695521,-74.104660,4.699883,-74.101456,183,184,20:09:11,20:31:57,0,1,0.379444,0.961919,1.078776,5.216667,3.433333,1.750000,0.033333,0
13143443,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699883,-74.101456,4.695547,-74.104680,184,183,20:58:47,21:22:29,0,1,0.395000,1.113022,1.350782,11.066667,11.066667,0.000000,0.000000,0

In [18]:
bogota_GPS_with_home = pd.merge(bogota_GPS, home_zone_true, left_on='DeviceId', right_on='DeviceId', how='left')

In [19]:
bogota_GPS_with_home

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,Weekend,...,RoadDistance,duration (min),walkTime (min),transitTime (min),waitingTime (min),transfers,Lat_home,Lon_home,Taz_home,Stays
0,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.625118,-74.125770,4.587117,-74.100170,383,501,08:08:11,15:57:24,0,...,8.422235,28.933333,8.933333,19.966667,0.033333,0,NaN,NaN,NaN,NaN
1,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.587117,-74.100170,4.588438,-74.100660,501,501,12:39:56,12:59:55,0,...,0.641031,2.716667,2.716667,0.000000,0.000000,0,NaN,NaN,NaN,NaN
2,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.588438,-74.100660,4.624916,-74.125450,501,383,13:20:20,20:31:11,0,...,7.139969,25.400000,5.933333,19.433333,0.033333,0,NaN,NaN,NaN,NaN
3,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.624916,-74.125450,4.586052,-74.098510,383,501,20:51:21,10:30:43,0,...,7.536019,32.500000,12.500000,19.966667,0.033333,0,NaN,NaN,NaN,NaN
4,a200dm00YWJhM2lnOmZxc3U5c3E2bXRuNG0=,4.586052,-74.098510,4.624972,-74.125560,501,383,14:45:27,00:28:40,0,...,7.860111,28.100000,8.633333,19.433333,0.033333,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13143439,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.700045,-74.101310,4.698133,-74.097560,184,184,12:30:32,12:41:54,0,...,0.616997,6.950000,6.950000,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0
13143440,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.698133,-74.097560,4.699910,-74.101550,184,184,13:21:21,13:56:34,0,...,0.613428,7.633333,7.633333,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0
13143441,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699910,-74.101550,4.695521,-74.104660,184,183,15:46:14,16:29:24,0,...,1.361477,10.933333,10.933333,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0
13143442,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.695521,-74.104660,4.699883,-74.101456,183,184,20:09:11,20:31:57,0,...,1.078776,5.216667,3.433333,1.750000,0.033333,0,-74.102954,4.697967,183.0,41.0
13143443,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699883,-74.101456,4.695547,-74.104680,184,183,20:58:47,21:22:29,0,...,1.350782,11.066667,11.066667,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0

In [20]:
bogota_GPS_with_home_true = bogota_GPS_with_home[bogota_GPS_with_home['Lat_home'].notna()]

In [21]:
bogota_GPS_with_home_true

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,Weekend,...,RoadDistance,duration (min),walkTime (min),transitTime (min),waitingTime (min),transfers,Lat_home,Lon_home,Taz_home,Stays
9,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.741007,-74.106606,4.745094,-74.110470,114,115,08:01:55,08:20:22,0,...,0.785153,10.633333,10.633333,0.000000,0.000000,0,-74.108389,4.742909,114.0,36.0
10,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745094,-74.110470,4.740927,-74.106530,115,114,18:37:33,21:33:11,0,...,0.883305,10.783333,10.783333,0.000000,0.000000,0,-74.108389,4.742909,114.0,36.0
11,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740927,-74.106530,4.745082,-74.110466,114,115,07:01:01,10:04:45,0,...,0.792002,10.783333,10.783333,0.000000,0.000000,0,-74.108389,4.742909,114.0,36.0
12,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745082,-74.110466,4.740935,-74.106550,115,114,11:10:40,16:51:00,0,...,0.879321,10.750000,10.750000,0.000000,0.000000,0,-74.108389,4.742909,114.0,36.0
13,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740935,-74.106550,4.739227,-74.084870,114,836,08:56:23,13:55:39,0,...,4.926316,22.400000,9.550000,12.816667,0.033333,0,-74.108389,4.742909,114.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13143439,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.700045,-74.101310,4.698133,-74.097560,184,184,12:30:32,12:41:54,0,...,0.616997,6.950000,6.950000,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0
13143440,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.698133,-74.097560,4.699910,-74.101550,184,184,13:21:21,13:56:34,0,...,0.613428,7.633333,7.633333,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0
13143441,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699910,-74.101550,4.695521,-74.104660,184,183,15:46:14,16:29:24,0,...,1.361477,10.933333,10.933333,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0
13143442,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.695521,-74.104660,4.699883,-74.101456,183,184,20:09:11,20:31:57,0,...,1.078776,5.216667,3.433333,1.750000,0.033333,0,-74.102954,4.697967,183.0,41.0
13143443,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699883,-74.101456,4.695547,-74.104680,184,183,20:58:47,21:22:29,0,...,1.350782,11.066667,11.066667,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0

In [22]:
bogota_GPS_with_home_true['Origin_home'] = bogota_GPS_with_home_true['OriginTaz'].eq(bogota_GPS_with_home_true['Taz_home']).astype(int)
bogota_GPS_with_home_true['Dest_home'] = bogota_GPS_with_home_true['DestinationTaz'].eq(bogota_GPS_with_home_true['Taz_home']).astype(int)

C:\Users\Abedini7\AppData\Local\Temp\ipykernel_14068\562810780.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bogota_GPS_with_home_true['Origin_home'] = bogota_GPS_with_home_true['OriginTaz'].eq(bogota_GPS_with_home_true['Taz_home']).astype(int)
C:\Users\Abedini7\AppData\Local\Temp\ipykernel_14068\562810780.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bogota_GPS_with_home_true['Dest_home'] = bogota_GPS_with_home_true['DestinationTaz'].eq(bogota_GPS_with_home_true['Taz_home']).astype(int)

In [23]:
bogota_GPS_with_home_true

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,Weekend,...,walkTime (min),transitTime (min),waitingTime (min),transfers,Lat_home,Lon_home,Taz_home,Stays,Origin_home,Dest_home
9,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.741007,-74.106606,4.745094,-74.110470,114,115,08:01:55,08:20:22,0,...,10.633333,0.000000,0.000000,0,-74.108389,4.742909,114.0,36.0,1,0
10,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745094,-74.110470,4.740927,-74.106530,115,114,18:37:33,21:33:11,0,...,10.783333,0.000000,0.000000,0,-74.108389,4.742909,114.0,36.0,0,1
11,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740927,-74.106530,4.745082,-74.110466,114,115,07:01:01,10:04:45,0,...,10.783333,0.000000,0.000000,0,-74.108389,4.742909,114.0,36.0,1,0
12,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745082,-74.110466,4.740935,-74.106550,115,114,11:10:40,16:51:00,0,...,10.750000,0.000000,0.000000,0,-74.108389,4.742909,114.0,36.0,0,1
13,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740935,-74.106550,4.739227,-74.084870,114,836,08:56:23,13:55:39,0,...,9.550000,12.816667,0.033333,0,-74.108389,4.742909,114.0,36.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13143439,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.700045,-74.101310,4.698133,-74.097560,184,184,12:30:32,12:41:54,0,...,6.950000,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0,0,0
13143440,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.698133,-74.097560,4.699910,-74.101550,184,184,13:21:21,13:56:34,0,...,7.633333,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0,0,0
13143441,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699910,-74.101550,4.695521,-74.104660,184,183,15:46:14,16:29:24,0,...,10.933333,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0,0,1
13143442,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.695521,-74.104660,4.699883,-74.101456,183,184,20:09:11,20:31:57,0,...,3.433333,1.750000,0.033333,0,-74.102954,4.697967,183.0,41.0,1,0
13143443,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699883,-74.101456,4.695547,-74.104680,184,183,20:58:47,21:22:29,0,...,11.066667,0.000000,0.000000,0,-74.102954,4.697967,183.0,41.0,0,1

bogota_GPS_with_home_true['TripStartTime_group'] = bogota_GPS_with_home_true['TripStartTime'].apply(lambda x: 
    "Dawn" if (datetime.strptime("12:00 AM", "%I:%M %p") <= datetime.strptime(x, '%H:%M:%S') < datetime.strptime("6:00 AM", "%I:%M %p"))
    else "Morning_Peak" if (datetime.strptime("6:00 AM", "%I:%M %p") <= datetime.strptime(x, '%H:%M:%S') < datetime.strptime("9:00 AM", "%I:%M %p"))
    else "Morning_OffPeak" if (datetime.strptime("9:00 AM", "%I:%M %p") <= datetime.strptime(x, '%H:%M:%S') < datetime.strptime("12:00 PM", "%I:%M %p"))
    else "Afternoon" if (datetime.strptime("12:00 PM", "%I:%M %p") <= datetime.strptime(x, '%H:%M:%S') < datetime.strptime("5:00 PM", "%I:%M %p"))
    else "Evening_Peak" if (datetime.strptime("5:00 PM", "%I:%M %p") <= datetime.strptime(x, '%H:%M:%S') < datetime.strptime("8:00 PM", "%I:%M %p"))
    else "Night" if (datetime.strptime("8:00 PM", "%I:%M %p") <= datetime.strptime(x, '%H:%M:%S') <= datetime.strptime("11:59 PM", "%I:%M %p"))
    else None)

In [24]:
time_ranges = {
    (datetime.strptime("12:00 AM", "%I:%M %p"), datetime.strptime("6:00 AM", "%I:%M %p")): "Dawn",
    (datetime.strptime("6:00 AM", "%I:%M %p"), datetime.strptime("9:00 AM", "%I:%M %p")): "Morning_Peak",
    (datetime.strptime("9:00 AM", "%I:%M %p"), datetime.strptime("12:00 PM", "%I:%M %p")): "Morning_OffPeak",
    (datetime.strptime("12:00 PM", "%I:%M %p"), datetime.strptime("5:00 PM", "%I:%M %p")): "Afternoon",
    (datetime.strptime("5:00 PM", "%I:%M %p"), datetime.strptime("8:00 PM", "%I:%M %p")): "Evening_Peak",
    (datetime.strptime("8:00 PM", "%I:%M %p"), datetime.strptime("11:59 PM", "%I:%M %p")): "Night",
}

def get_time_group(time_str):
    time_obj = datetime.strptime(time_str, '%H:%M:%S')
    for time_range, label in time_ranges.items():
        if time_range[0] <= time_obj < time_range[1]:
            return label
    return None

bogota_GPS_with_home_true['TripStartTime_group'] = bogota_GPS_with_home_true['TripStartTime'].apply(get_time_group)

C:\Users\Abedini7\AppData\Local\Temp\ipykernel_14068\738497537.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bogota_GPS_with_home_true['TripStartTime_group'] = bogota_GPS_with_home_true['TripStartTime'].apply(get_time_group)

In [25]:
bogota_GPS_with_home_true['TripEndTime_group'] = bogota_GPS_with_home_true['TripEndTime'].apply(get_time_group)

C:\Users\Abedini7\AppData\Local\Temp\ipykernel_14068\32627030.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bogota_GPS_with_home_true['TripEndTime_group'] = bogota_GPS_with_home_true['TripEndTime'].apply(get_time_group)

In [26]:
bogota_GPS_with_home_true.TripStartTime_group

9              Morning_Peak
10             Evening_Peak
11             Morning_Peak
12          Morning_OffPeak
13             Morning_Peak
                 ...
13143439          Afternoon
13143440          Afternoon
13143441          Afternoon
13143442              Night
13143443              Night
Name: TripStartTime_group, Length: 10699015, dtype: object

In [27]:
# create one-hot encoded columns
one_hot_df1 = pd.get_dummies(bogota_GPS_with_home_true.TripStartTime_group, prefix='StartTime')
one_hot_df2 = pd.get_dummies(bogota_GPS_with_home_true.TripEndTime_group, prefix='EndTime')

# join the original dataframe with the one-hot encoded columns
bogota_GPS_with_home_true = bogota_GPS_with_home_true.join(one_hot_df1)
bogota_GPS_with_home_true = bogota_GPS_with_home_true.join(one_hot_df2)

In [28]:
bogota_GPS_with_home_true = bogota_GPS_with_home_true.drop(['TripEndTime_group','TripStartTime_group'], axis=1)

In [29]:
bogota_GPS_with_home_true.columns

Index(['DeviceId', 'OriginLat', 'OriginLon', 'DestinationLat',
       'DestinationLon', 'OriginTaz', 'DestinationTaz', 'TripStartTime',
       'TripEndTime', 'Weekend', 'Weekday', 'TripDuration', 'RoadTime',
       'RoadDistance', 'duration (min)', 'walkTime (min)', 'transitTime (min)',
       'waitingTime (min)', 'transfers', 'Lat_home', 'Lon_home', 'Taz_home',
       'Stays', 'Origin_home', 'Dest_home', 'StartTime_Afternoon',
       'StartTime_Dawn', 'StartTime_Evening_Peak', 'StartTime_Morning_OffPeak',
       'StartTime_Morning_Peak', 'StartTime_Night', 'EndTime_Afternoon',
       'EndTime_Dawn', 'EndTime_Evening_Peak', 'EndTime_Morning_OffPeak',
       'EndTime_Morning_Peak', 'EndTime_Night'],
      dtype='object')

### Join Socio-demo to the dataframe

In [30]:
one_hot_df3 = pd.get_dummies(socio_demo.NSE, prefix='NSE')
socio_demo = socio_demo.join(one_hot_df3)

In [31]:
socio_demo

,DeviceId,Lon,Lat,Stays,Clusters,hex_o,Poblacion,area_m2,NSE,NSE3,NSE_1 Alto,NSE_2 Medio-Alto,NSE_3 Medio,NSE_4 Medio-Bajo,NSE_5 Bajo
0,NTZzaHUxcDNjcmV1ZDozOG5nZ21ncTgxZjBt,-74.183817,4.566663,27,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo,0,0,0,0,1
1,NW5zbjMwaDV0N2puMjphbWpsazdpODZ1NnAy,-74.177602,4.571539,29,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo,0,0,0,0,1
2,NTE4aGNlcms3ZHB0djpkajhrdWNzMDE2ZDA5,-74.181735,4.573120,37,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo,0,0,0,0,1
3,NTMwajU5aG9pa3BhbjpkdmdiNm9jOWNydHNy,-74.183087,4.567099,13,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo,0,0,0,0,1
4,NXBsczdpZ2dpbWVpOTpiN3ZhcGVrY3F1bmtv,-74.180045,4.570669,25,1,8866e09133fffff,8593,768966,5 Bajo,3 Bajo,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286639,ZnRucXZiNzdtbnI5bTo4MjlpcXJvZ3YzNGJ2,-74.155588,4.587725,42,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio,0,1,0,0,0
286640,ZTljMWFkMzZpamVzajplYjF2c2Q5dnRmN2Vs,-74.155067,4.586321,49,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio,0,1,0,0,0
286641,ZTM4M3NmNjlhMnUydTpkZ2JnYWNmdG0xc3Rj,-74.160132,4.585009,11,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio,0,1,0,0,0
286642,ZTdoMjYzMWswaXUyODo2MXJoYTdhdnE2c2tn,-74.153778,4.587746,15,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio,0,1,0,0,0
286643,ZTk1Z2NzNW8zaHBoYTplMmNmNDdtN3Rla3Jh,-74.157386,4.582126,34,1,8866e0911bfffff,22651,768616,2 Medio-Alto,2 Medio,0,1,0,0,0

In [32]:
socio_demo = socio_demo.drop(['Lon', 'Lat', 'Stays', 'Clusters', 'hex_o', 'Poblacion',
       'area_m2', 'NSE','NSE3'], axis=1)

In [33]:
socio_demo

,DeviceId,NSE_1 Alto,NSE_2 Medio-Alto,NSE_3 Medio,NSE_4 Medio-Bajo,NSE_5 Bajo
0,NTZzaHUxcDNjcmV1ZDozOG5nZ21ncTgxZjBt,0,0,0,0,1
1,NW5zbjMwaDV0N2puMjphbWpsazdpODZ1NnAy,0,0,0,0,1
2,NTE4aGNlcms3ZHB0djpkajhrdWNzMDE2ZDA5,0,0,0,0,1
3,NTMwajU5aG9pa3BhbjpkdmdiNm9jOWNydHNy,0,0,0,0,1
4,NXBsczdpZ2dpbWVpOTpiN3ZhcGVrY3F1bmtv,0,0,0,0,1
...,...,...,...,...,...,...
286639,ZnRucXZiNzdtbnI5bTo4MjlpcXJvZ3YzNGJ2,0,1,0,0,0
286640,ZTljMWFkMzZpamVzajplYjF2c2Q5dnRmN2Vs,0,1,0,0,0
286641,ZTM4M3NmNjlhMnUydTpkZ2JnYWNmdG0xc3Rj,0,1,0,0,0
286642,ZTdoMjYzMWswaXUyODo2MXJoYTdhdnE2c2tn,0,1,0,0,0
286643,ZTk1Z2NzNW8zaHBoYTplMmNmNDdtN3Rla3Jh,0,1,0,0,0

In [34]:
bogota_GPS_with_home_true

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,Weekend,...,StartTime_Evening_Peak,StartTime_Morning_OffPeak,StartTime_Morning_Peak,StartTime_Night,EndTime_Afternoon,EndTime_Dawn,EndTime_Evening_Peak,EndTime_Morning_OffPeak,EndTime_Morning_Peak,EndTime_Night
9,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.741007,-74.106606,4.745094,-74.110470,114,115,08:01:55,08:20:22,0,...,0,0,1,0,0,0,0,0,1,0
10,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745094,-74.110470,4.740927,-74.106530,115,114,18:37:33,21:33:11,0,...,1,0,0,0,0,0,0,0,0,1
11,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740927,-74.106530,4.745082,-74.110466,114,115,07:01:01,10:04:45,0,...,0,0,1,0,0,0,0,1,0,0
12,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745082,-74.110466,4.740935,-74.106550,115,114,11:10:40,16:51:00,0,...,0,1,0,0,1,0,0,0,0,0
13,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740935,-74.106550,4.739227,-74.084870,114,836,08:56:23,13:55:39,0,...,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13143439,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.700045,-74.101310,4.698133,-74.097560,184,184,12:30:32,12:41:54,0,...,0,0,0,0,1,0,0,0,0,0
13143440,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.698133,-74.097560,4.699910,-74.101550,184,184,13:21:21,13:56:34,0,...,0,0,0,0,1,0,0,0,0,0
13143441,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699910,-74.101550,4.695521,-74.104660,184,183,15:46:14,16:29:24,0,...,0,0,0,0,1,0,0,0,0,0
13143442,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.695521,-74.104660,4.699883,-74.101456,183,184,20:09:11,20:31:57,0,...,0,0,0,1,0,0,0,0,0,1
13143443,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699883,-74.101456,4.695547,-74.104680,184,183,20:58:47,21:22:29,0,...,0,0,0,1,0,0,0,0,0,1

In [35]:
bogota_GPS_with_home_true_socio = pd.merge(bogota_GPS_with_home_true, socio_demo, left_on='DeviceId', right_on='DeviceId', how='left')

In [36]:
bogota_GPS_with_home_true_socio

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,Weekend,...,EndTime_Dawn,EndTime_Evening_Peak,EndTime_Morning_OffPeak,EndTime_Morning_Peak,EndTime_Night,NSE_1 Alto,NSE_2 Medio-Alto,NSE_3 Medio,NSE_4 Medio-Bajo,NSE_5 Bajo
0,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.741007,-74.106606,4.745094,-74.110470,114,115,08:01:55,08:20:22,0,...,0,0,0,1,0,0.0,0.0,0.0,1.0,0.0
1,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745094,-74.110470,4.740927,-74.106530,115,114,18:37:33,21:33:11,0,...,0,0,0,0,1,0.0,0.0,0.0,1.0,0.0
2,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740927,-74.106530,4.745082,-74.110466,114,115,07:01:01,10:04:45,0,...,0,0,1,0,0,0.0,0.0,0.0,1.0,0.0
3,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745082,-74.110466,4.740935,-74.106550,115,114,11:10:40,16:51:00,0,...,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0
4,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740935,-74.106550,4.739227,-74.084870,114,836,08:56:23,13:55:39,0,...,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699010,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.700045,-74.101310,4.698133,-74.097560,184,184,12:30:32,12:41:54,0,...,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0
10699011,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.698133,-74.097560,4.699910,-74.101550,184,184,13:21:21,13:56:34,0,...,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0
10699012,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699910,-74.101550,4.695521,-74.104660,184,183,15:46:14,16:29:24,0,...,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0
10699013,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.695521,-74.104660,4.699883,-74.101456,183,184,20:09:11,20:31:57,0,...,0,0,0,0,1,0.0,1.0,0.0,0.0,0.0
10699014,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699883,-74.101456,4.695547,-74.104680,184,183,20:58:47,21:22:29,0,...,0,0,0,0,1,0.0,1.0,0.0,0.0,0.0

In [37]:
bogota_GPS_with_home_true_socio['NSE_5 Bajo'].value_counts()

0.0    8809856
1.0    1093117
Name: NSE_5 Bajo, dtype: int64

### merge number of transit stops

In [38]:
num_transit_stops['Area (sq. m)'] = num_transit_stops['Area (sq. m)']/1000000

In [39]:
num_transit_stops['Total length of transit routes (m)'] = num_transit_stops['Total length of transit routes (m)']/1000

In [40]:
num_transit_stops['Total number of transit stops'] = num_transit_stops['Total number of transit stops']/num_transit_stops['Area (sq. m)']
num_transit_stops['Number of Troncal stops'] = num_transit_stops['Number of Troncal stops']/num_transit_stops['Area (sq. m)']
num_transit_stops['Number of Alimentadores stops'] = num_transit_stops['Number of Alimentadores stops']/num_transit_stops['Area (sq. m)']
num_transit_stops['Number of Complementaria stops'] = num_transit_stops['Number of Complementaria stops']/num_transit_stops['Area (sq. m)']
num_transit_stops['Number of Especial stops'] = num_transit_stops['Number of Especial stops']/num_transit_stops['Area (sq. m)']
num_transit_stops['Total length of transit routes (m)'] = num_transit_stops['Total length of transit routes (m)']/num_transit_stops['Area (sq. m)']

In [41]:
num_transit_stops = num_transit_stops.rename({'Total number of transit stops': 'total_num_transit_stops_perKM2', 
                                              'Number of Troncal stops': 'num_troncal_stops_perKM2',
                                             'Number of Alimentadores stops':'num_alimentadores_stops_perKM2',
                                             'Number of Complementaria stops':'num_complementaria_stops_perKM2',
                                             'Number of Especial stops':'num_especial_stops_perKM2',
                                             'Total length of transit routes (m)':'total_length_transit_km_perKM2',
                                             'Area (sq. m)':'Area (sq. km)'}, axis=1)
num_transit_stops

,ZAT,Area (sq. km),total_num_transit_stops_perKM2,num_troncal_stops_perKM2,num_alimentadores_stops_perKM2,num_complementaria_stops_perKM2,num_especial_stops_perKM2,total_length_transit_km_perKM2
0,1,3.271071,0.000000,0.000000,0.0,0.0,0.0,0.062597
1,2,2.246763,0.000000,0.000000,0.0,0.0,0.0,0.000000
2,3,1.113507,1.796127,1.796127,0.0,0.0,0.0,1.198137
3,4,0.953726,2.097039,2.097039,0.0,0.0,0.0,7.872514
4,5,0.332649,0.000000,0.000000,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...
1136,1904,40.064475,0.000000,0.000000,0.0,0.0,0.0,0.000000
1137,1905,71.271360,0.000000,0.000000,0.0,0.0,0.0,0.000000
1138,1906,178.296606,0.000000,0.000000,0.0,0.0,0.0,0.000000
1139,1907,178.296606,0.000000,0.000000,0.0,0.0,0.0,0.000000
1140,1908,55.305804,0.000000,0.000000,0.0,0.0,0.0,0.000000

In [42]:
num_transit_stops_origin = num_transit_stops.add_suffix('_origin')
num_transit_stops_dest = num_transit_stops.add_suffix('_dest')

In [43]:
num_transit_stops_dest

,ZAT_dest,Area (sq. km)_dest,total_num_transit_stops_perKM2_dest,num_troncal_stops_perKM2_dest,num_alimentadores_stops_perKM2_dest,num_complementaria_stops_perKM2_dest,num_especial_stops_perKM2_dest,total_length_transit_km_perKM2_dest
0,1,3.271071,0.000000,0.000000,0.0,0.0,0.0,0.062597
1,2,2.246763,0.000000,0.000000,0.0,0.0,0.0,0.000000
2,3,1.113507,1.796127,1.796127,0.0,0.0,0.0,1.198137
3,4,0.953726,2.097039,2.097039,0.0,0.0,0.0,7.872514
4,5,0.332649,0.000000,0.000000,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...
1136,1904,40.064475,0.000000,0.000000,0.0,0.0,0.0,0.000000
1137,1905,71.271360,0.000000,0.000000,0.0,0.0,0.0,0.000000
1138,1906,178.296606,0.000000,0.000000,0.0,0.0,0.0,0.000000
1139,1907,178.296606,0.000000,0.000000,0.0,0.0,0.0,0.000000
1140,1908,55.305804,0.000000,0.000000,0.0,0.0,0.0,0.000000

In [44]:
bogota_GPS_with_home_true_socio

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,Weekend,...,EndTime_Dawn,EndTime_Evening_Peak,EndTime_Morning_OffPeak,EndTime_Morning_Peak,EndTime_Night,NSE_1 Alto,NSE_2 Medio-Alto,NSE_3 Medio,NSE_4 Medio-Bajo,NSE_5 Bajo
0,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.741007,-74.106606,4.745094,-74.110470,114,115,08:01:55,08:20:22,0,...,0,0,0,1,0,0.0,0.0,0.0,1.0,0.0
1,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745094,-74.110470,4.740927,-74.106530,115,114,18:37:33,21:33:11,0,...,0,0,0,0,1,0.0,0.0,0.0,1.0,0.0
2,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740927,-74.106530,4.745082,-74.110466,114,115,07:01:01,10:04:45,0,...,0,0,1,0,0,0.0,0.0,0.0,1.0,0.0
3,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.745082,-74.110466,4.740935,-74.106550,115,114,11:10:40,16:51:00,0,...,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0
4,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740935,-74.106550,4.739227,-74.084870,114,836,08:56:23,13:55:39,0,...,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699010,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.700045,-74.101310,4.698133,-74.097560,184,184,12:30:32,12:41:54,0,...,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0
10699011,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.698133,-74.097560,4.699910,-74.101550,184,184,13:21:21,13:56:34,0,...,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0
10699012,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699910,-74.101550,4.695521,-74.104660,184,183,15:46:14,16:29:24,0,...,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0
10699013,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.695521,-74.104660,4.699883,-74.101456,183,184,20:09:11,20:31:57,0,...,0,0,0,0,1,0.0,1.0,0.0,0.0,0.0
10699014,ZzZzZGluYTZ0cGxjOmR1anRqaDZldmNkdmg=,4.699883,-74.101456,4.695547,-74.104680,184,183,20:58:47,21:22:29,0,...,0,0,0,0,1,0.0,1.0,0.0,0.0,0.0

In [45]:
bogota_GPS_with_home_true_socio_num_transit = bogota_GPS_with_home_true_socio.merge(num_transit_stops_origin, how='inner', left_on='OriginTaz', right_on='ZAT_origin')

In [46]:
bogota_GPS_with_home_true_socio_num_transit = bogota_GPS_with_home_true_socio_num_transit.merge(num_transit_stops_dest, how='inner', left_on='DestinationTaz', right_on='ZAT_dest')

In [47]:
bogota_GPS_with_home_true_socio_num_transit

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,Weekend,...,num_especial_stops_perKM2_origin,total_length_transit_km_perKM2_origin,ZAT_dest,Area (sq. km)_dest,total_num_transit_stops_perKM2_dest,num_troncal_stops_perKM2_dest,num_alimentadores_stops_perKM2_dest,num_complementaria_stops_perKM2_dest,num_especial_stops_perKM2_dest,total_length_transit_km_perKM2_dest
0,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.741007,-74.106606,4.745094,-74.110470,114,115,08:01:55,08:20:22,0,...,0.0,19.943716,115,1.046491,42.045283,42.045283,0.0,0.0,0.0,26.223945
1,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740927,-74.106530,4.745082,-74.110466,114,115,07:01:01,10:04:45,0,...,0.0,19.943716,115,1.046491,42.045283,42.045283,0.0,0.0,0.0,26.223945
2,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740973,-74.106540,4.745284,-74.110520,114,115,10:52:52,16:43:04,0,...,0.0,19.943716,115,1.046491,42.045283,42.045283,0.0,0.0,0.0,26.223945
3,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740980,-74.106570,4.745112,-74.110520,114,115,11:21:31,16:06:53,0,...,0.0,19.943716,115,1.046491,42.045283,42.045283,0.0,0.0,0.0,26.223945
4,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740964,-74.106580,4.745061,-74.110480,114,115,10:04:58,10:55:01,0,...,0.0,19.943716,115,1.046491,42.045283,42.045283,0.0,0.0,0.0,26.223945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699010,OGdjcW5rNTQ4a2h0YjphMjZkaGszamdzcWZu,4.529459,-74.084370,4.530284,-74.081535,696,697,22:07:54,22:08:30,1,...,0.0,7.698992,697,0.182111,0.000000,0.000000,0.0,0.0,0.0,0.000000
10699011,OGdjcW5rNTQ4a2h0YjphMjZkaGszamdzcWZu,4.529420,-74.084530,4.530371,-74.081560,696,697,22:46:52,22:47:22,1,...,0.0,7.698992,697,0.182111,0.000000,0.000000,0.0,0.0,0.0,0.000000
10699012,OWxsaGdwZnY5YW1qOjJsajRxMDFuYWplcDA=,4.536099,-74.080520,4.531193,-74.080430,698,697,16:47:23,16:48:05,1,...,0.0,5.717046,697,0.182111,0.000000,0.000000,0.0,0.0,0.0,0.000000
10699013,ZG45bW12dXR0b2llaDo1YXZ0dGJ1Yjh2dW9v,4.525525,-74.087620,4.523111,-74.085420,693,695,12:50:53,12:52:24,1,...,0.0,11.463048,695,0.063282,0.000000,0.000000,0.0,0.0,0.0,2.244057
10699014,YzZvNmU5ODVnMmk0cjo2M3Y3c3Y3Mjk4amYz,4.527107,-74.087074,4.524916,-74.086920,696,695,05:53:16,05:54:38,1,...,0.0,7.698992,695,0.063282,0.000000,0.000000,0.0,0.0,0.0,2.244057

### Join employment data

In [48]:
merge1=pd.merge(bogota_GPS_with_home_true_socio_num_transit, bgt_TAZ_O, left_on='OriginTaz', right_on='ZAT_O', how='left')

In [49]:
merge2=pd.merge(merge1, bgt_TAZ_D, left_on='DestinationTaz', right_on='ZAT_D', how='left')

In [50]:
merge2.columns

Index(['DeviceId', 'OriginLat', 'OriginLon', 'DestinationLat',
       'DestinationLon', 'OriginTaz', 'DestinationTaz', 'TripStartTime',
       'TripEndTime', 'Weekend', 'Weekday', 'TripDuration', 'RoadTime',
       'RoadDistance', 'duration (min)', 'walkTime (min)', 'transitTime (min)',
       'waitingTime (min)', 'transfers', 'Lat_home', 'Lon_home', 'Taz_home',
       'Stays', 'Origin_home', 'Dest_home', 'StartTime_Afternoon',
       'StartTime_Dawn', 'StartTime_Evening_Peak', 'StartTime_Morning_OffPeak',
       'StartTime_Morning_Peak', 'StartTime_Night', 'EndTime_Afternoon',
       'EndTime_Dawn', 'EndTime_Evening_Peak', 'EndTime_Morning_OffPeak',
       'EndTime_Morning_Peak', 'EndTime_Night', 'NSE_1 Alto',
       'NSE_2 Medio-Alto', 'NSE_3 Medio', 'NSE_4 Medio-Bajo', 'NSE_5 Bajo',
       'ZAT_origin', 'Area (sq. km)_origin',
       'total_num_transit_stops_perKM2_origin',
       'num_troncal_stops_perKM2_origin',
       'num_alimentadores_stops_perKM2_origin',
       'num_complementaria_stops_perKM2_origin',
       'num_especial_stops_perKM2_origin',
       'total_length_transit_km_perKM2_origin', 'ZAT_dest',
       'Area (sq. km)_dest', 'total_num_transit_stops_perKM2_dest',
       'num_troncal_stops_perKM2_dest', 'num_alimentadores_stops_perKM2_dest',
       'num_complementaria_stops_perKM2_dest',
       'num_especial_stops_perKM2_dest', 'total_length_transit_km_perKM2_dest',
       'ZAT_O', 'Population_O', 'Area_km2_O', 'PopPerKM2', 'Agro2018_perZAT_O',
       'Com2018_perZAT_O', 'Ind2018_perZAT_O', 'Serv2018_perZAT_O',
       'Other2018_perZAT_O', 'Agro2018_perZAT_perKM2_O',
       'Com2018_perZAT_perKM2_O', 'Ind2018_perZAT_perKM2_O',
       'Serv2018_perZAT_perKM2_O', 'Other2018_perZAT_perKM2_O', 'ZAT_D',
       'Population_D', 'Area_km2_D', 'PopPerKM2_D', 'Agro2018_perZAT_D',
       'Com2018_perZAT_D', 'Ind2018_perZAT_D', 'Serv2018_perZAT_D',
       'Other2018_perZAT_D', 'Agro2018_perZAT_perKM2_D',
       'Com2018_perZAT_perKM2_D', 'Ind2018_perZAT_perKM2_D',
       'Serv2018_perZAT_perKM2_D', 'Other2018_perZAT_perKM2_D'],
      dtype='object')

### Clear the features

In [51]:
GPS_features = merge2

In [52]:
GPS_features['intra_zonal_trip'] = GPS_features['OriginTaz'].eq(GPS_features['DestinationTaz']).astype(int)

In [53]:
GPS_features = GPS_features.rename(columns={'Agro2018_perZAT_perKM2_O':'Agro2018_perZAT_perKM2_origin',
                                            'Com2018_perZAT_perKM2_O':'Com2018_perZAT_perKM2_origin', 
                                            'Ind2018_perZAT_perKM2_O':'Ind2018_perZAT_perKM2_origin',
                                            'Serv2018_perZAT_perKM2_O':'Serv2018_perZAT_perKM2_origin', 
                                            'Other2018_perZAT_perKM2_O':'Other2018_perZAT_perKM2_origin', 
                                            'Agro2018_perZAT_perKM2_D':'Agro2018_perZAT_perKM2_dest',
                                           'Com2018_perZAT_perKM2_D':'Com2018_perZAT_perKM2_dest',
                                            'Ind2018_perZAT_perKM2_D':'Ind2018_perZAT_perKM2_dest',
                                           'Serv2018_perZAT_perKM2_D':'Serv2018_perZAT_perKM2_dest', 
                                            'Other2018_perZAT_perKM2_D':'Other2018_perZAT_perKM2_dest'})

In [54]:
GPS_features

,DeviceId,OriginLat,OriginLon,DestinationLat,DestinationLon,OriginTaz,DestinationTaz,TripStartTime,TripEndTime,Weekend,...,Com2018_perZAT_D,Ind2018_perZAT_D,Serv2018_perZAT_D,Other2018_perZAT_D,Agro2018_perZAT_perKM2_dest,Com2018_perZAT_perKM2_dest,Ind2018_perZAT_perKM2_dest,Serv2018_perZAT_perKM2_dest,Other2018_perZAT_perKM2_dest,intra_zonal_trip
0,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.741007,-74.106606,4.745094,-74.110470,114,115,08:01:55,08:20:22,0,...,453.500,282.250,524.750,40.500,6.450,433.353,269.711,501.438,38.701,0
1,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740927,-74.106530,4.745082,-74.110466,114,115,07:01:01,10:04:45,0,...,453.500,282.250,524.750,40.500,6.450,433.353,269.711,501.438,38.701,0
2,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740973,-74.106540,4.745284,-74.110520,114,115,10:52:52,16:43:04,0,...,453.500,282.250,524.750,40.500,6.450,433.353,269.711,501.438,38.701,0
3,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740980,-74.106570,4.745112,-74.110520,114,115,11:21:31,16:06:53,0,...,453.500,282.250,524.750,40.500,6.450,433.353,269.711,501.438,38.701,0
4,a201Nzh1ZzVvNzNiOmx2MTduM3Z0b3A1cQ==,4.740964,-74.106580,4.745061,-74.110480,114,115,10:04:58,10:55:01,0,...,453.500,282.250,524.750,40.500,6.450,433.353,269.711,501.438,38.701,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699010,OGdjcW5rNTQ4a2h0YjphMjZkaGszamdzcWZu,4.529459,-74.084370,4.530284,-74.081535,696,697,22:07:54,22:08:30,1,...,77.357,54.714,85.071,6.857,2.353,424.780,300.444,467.140,37.654,0
10699011,OGdjcW5rNTQ4a2h0YjphMjZkaGszamdzcWZu,4.529420,-74.084530,4.530371,-74.081560,696,697,22:46:52,22:47:22,1,...,77.357,54.714,85.071,6.857,2.353,424.780,300.444,467.140,37.654,0
10699012,OWxsaGdwZnY5YW1qOjJsajRxMDFuYWplcDA=,4.536099,-74.080520,4.531193,-74.080430,698,697,16:47:23,16:48:05,1,...,77.357,54.714,85.071,6.857,2.353,424.780,300.444,467.140,37.654,0
10699013,ZG45bW12dXR0b2llaDo1YXZ0dGJ1Yjh2dW9v,4.525525,-74.087620,4.523111,-74.085420,693,695,12:50:53,12:52:24,1,...,64.667,55.444,72.778,5.333,10.535,1021.886,876.153,1150.060,84.279,0
10699014,YzZvNmU5ODVnMmk0cjo2M3Y3c3Y3Mjk4amYz,4.527107,-74.087074,4.524916,-74.086920,696,695,05:53:16,05:54:38,1,...,64.667,55.444,72.778,5.333,10.535,1021.886,876.153,1150.060,84.279,0

In [55]:
GPS_features['duration (min)'] = GPS_features['duration (min)']/60
GPS_features['walkTime (min)'] = GPS_features['walkTime (min)']/60
GPS_features['transitTime (min)'] = GPS_features['transitTime (min)']/60
GPS_features['waitingTime (min)'] = GPS_features['waitingTime (min)']/60

In [56]:
import math

def haversine(lat1, lon1, lat2, lon2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])

    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.asin(math.sqrt(a)) 
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles
    return c * r

In [57]:
# calculate the distance between the two points in each row
GPS_features['distance'] = GPS_features.apply(
    lambda row: haversine(row['OriginLon'], row['OriginLat'], row['DestinationLon'], row['DestinationLat']), axis=1)

In [58]:
GPS_features_final = GPS_features.drop(['TripStartTime', 'TripEndTime', 'RoadDistance',
                                        'walkTime (min)', 'transitTime (min)','waitingTime (min)',
                                        'DeviceId', 'OriginTaz', 'DestinationTaz',
                                       'Lat_home', 'Lon_home', 'Taz_home','Stays',
                                        'Area (sq. km)_origin',
                                        'Area (sq. km)_dest',
                                        'ZAT_O', 'Population_O', 'Area_km2_O',
                                        'ZAT_D', 'Population_D', 'Area_km2_D',
                                       'StartTime_Dawn','EndTime_Dawn',
                                        'total_num_transit_stops_perKM2_origin',
                                        'total_num_transit_stops_perKM2_dest', 
                                        'Agro2018_perZAT_O', 'Com2018_perZAT_O',
                                        'Ind2018_perZAT_O', 'Serv2018_perZAT_O', 'Other2018_perZAT_O',
                                        'Agro2018_perZAT_D','Com2018_perZAT_D', 
                                        'Ind2018_perZAT_D', 'Serv2018_perZAT_D','Other2018_perZAT_D',
                                        'Other2018_perZAT_perKM2_origin','Other2018_perZAT_perKM2_dest'
                                        
                                       ],axis=1)

#'OriginLat', 'OriginLon', 'DestinationLat','DestinationLon'

In [59]:
GPS_features_final.columns

Index(['OriginLat', 'OriginLon', 'DestinationLat', 'DestinationLon', 'Weekend',
       'Weekday', 'TripDuration', 'RoadTime', 'duration (min)', 'transfers',
       'Origin_home', 'Dest_home', 'StartTime_Afternoon',
       'StartTime_Evening_Peak', 'StartTime_Morning_OffPeak',
       'StartTime_Morning_Peak', 'StartTime_Night', 'EndTime_Afternoon',
       'EndTime_Evening_Peak', 'EndTime_Morning_OffPeak',
       'EndTime_Morning_Peak', 'EndTime_Night', 'NSE_1 Alto',
       'NSE_2 Medio-Alto', 'NSE_3 Medio', 'NSE_4 Medio-Bajo', 'NSE_5 Bajo',
       'ZAT_origin', 'num_troncal_stops_perKM2_origin',
       'num_alimentadores_stops_perKM2_origin',
       'num_complementaria_stops_perKM2_origin',
       'num_especial_stops_perKM2_origin',
       'total_length_transit_km_perKM2_origin', 'ZAT_dest',
       'num_troncal_stops_perKM2_dest', 'num_alimentadores_stops_perKM2_dest',
       'num_complementaria_stops_perKM2_dest',
       'num_especial_stops_perKM2_dest', 'total_length_transit_km_perKM2_dest',
       'PopPerKM2', 'Agro2018_perZAT_perKM2_origin',
       'Com2018_perZAT_perKM2_origin', 'Ind2018_perZAT_perKM2_origin',
       'Serv2018_perZAT_perKM2_origin', 'PopPerKM2_D',
       'Agro2018_perZAT_perKM2_dest', 'Com2018_perZAT_perKM2_dest',
       'Ind2018_perZAT_perKM2_dest', 'Serv2018_perZAT_perKM2_dest',
       'intra_zonal_trip', 'distance'],
      dtype='object')

Survey feature names
'Unnamed: 0', 'Trip_TravelTime_Length_hour', 'Trip_Weekday',
       'Trip_Weekend', 'Trip_Occasional', 'RoadTime', 'PopPerKM2_ZAT_Orig',
       'PopPerKM2_ZAT_Dest', 'Agro2018_perZAT_perKM2_orig',
       'Com2018_perZAT_perKM2_orig', 'Ind2018_perZAT_perKM2_orig',
       'Serv2018_perZAT_perKM2_orig', 'Agro2018_perZAT_perKM2_dest',
       'Com2018_perZAT_perKM2_dest', 'Ind2018_perZAT_perKM2_dest',
       'Serv2018_perZAT_perKM2_dest', 'Mode', 'origin_taz', 'dest_taz',
       'duration (h)', 'transfers', 'num_troncal_stops_perKM2_origin',
       'num_alimentadores_stops_perKM2_origin',
       'num_complementaria_stops_perKM2_origin',
       'num_especial_stops_perKM2_origin',
       'total_length_transit_km_perKM2_origin',
       'num_troncal_stops_perKM2_dest', 'num_alimentadores_stops_perKM2_dest',
       'num_complementaria_stops_perKM2_dest',
       'num_especial_stops_perKM2_dest', 'total_length_transit_km_perKM2_dest',
       'NSE_1 Alto', 'NSE_2 Medio-Alto', 'NSE_3 Medio', 'NSE_4 Medio-Bajo',
       'NSE_5 Bajo', 'Origin_Home', 'StartTime_MorningPeak',
       'StartTime_MorningOffPeak', 'StartTime_Afternoon',
       'StartTime_EveningPeak', 'StartTime_Night', 'Dest_Home',
       'EndTime_MorningPeak', 'EndTime_MorningOffPeak', 'EndTime_Afternoon',
       'EndTime_EveningPeak', 'EndTime_Night', 'Mode_Active', 'Mode_Other',
       'Mode_Private', 'Mode_Transit'

In [60]:
# Rename the columns using a dictionary
GPS_features_final = GPS_features_final.rename(columns={

'TripDuration':'Trip_TravelTime_Length_hour', 
'Weekend':'Trip_Weekend', 
'Weekday':'Trip_Weekday',
       'RoadTime':'RoadTime', 
    'duration (min)':'duration (h)', 
        'transfers':'transfers', 
        'Origin_home':'Origin_Home',
       'Dest_home':'Dest_Home',
    'StartTime_Afternoon':'StartTime_Afternoon', 
       'StartTime_Evening_Peak':'StartTime_EveningPeak', 
        'StartTime_Morning_OffPeak':'StartTime_MorningOffPeak',
       'StartTime_Morning_Peak':'StartTime_MorningPeak',
    'StartTime_Night':'StartTime_Night', 
    'EndTime_Afternoon':'EndTime_Afternoon',
        'EndTime_Evening_Peak':'EndTime_EveningPeak', 
        'EndTime_Morning_OffPeak':'EndTime_MorningOffPeak',
       'EndTime_Morning_Peak':'EndTime_MorningPeak', 
    'EndTime_Night':'EndTime_Night', 
       'PopPerKM2':'PopPerKM2_ZAT_Orig', 
    'PopPerKM2_D':'PopPerKM2_ZAT_Dest', 
    'ZAT_origin':'origin_taz', 
    'ZAT_dest':'dest_taz',
    'Agro2018_perZAT_perKM2_origin':'Agro2018_perZAT_perKM2_orig',
       'Com2018_perZAT_perKM2_origin':'Com2018_perZAT_perKM2_orig', 
    'Ind2018_perZAT_perKM2_origin': 'Ind2018_perZAT_perKM2_orig',
       'Serv2018_perZAT_perKM2_origin':'Serv2018_perZAT_perKM2_orig',
    'Other2018_perZAT_perKM2_origin':'Other2018_perZAT_perKM2_orig',
})

In [61]:
GPS_features_final.describe()

,OriginLat,OriginLon,DestinationLat,DestinationLon,Trip_Weekend,Trip_Weekday,Trip_TravelTime_Length_hour,RoadTime,duration (h),transfers,...,Com2018_perZAT_perKM2_orig,Ind2018_perZAT_perKM2_orig,Serv2018_perZAT_perKM2_orig,PopPerKM2_ZAT_Dest,Agro2018_perZAT_perKM2_dest,Com2018_perZAT_perKM2_dest,Ind2018_perZAT_perKM2_dest,Serv2018_perZAT_perKM2_dest,intra_zonal_trip,distance
count,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,...,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07,1.069902e+07
mean,4.668188e+00,-7.411326e+01,4.668209e+00,-7.411315e+01,2.571729e-01,7.428271e-01,4.121422e+00,7.044908e+00,4.254054e-01,1.531781e-01,...,7.173517e+02,4.010837e+02,1.066606e+03,2.226581e+04,3.819196e+01,7.185723e+02,4.015423e+02,1.069877e+03,2.242388e-01,3.463205e+00
std,9.549081e-02,6.891060e-02,9.543401e-02,6.887962e-02,4.370755e-01,4.370755e-01,1.531886e+01,8.847543e+00,4.612882e-01,7.135093e-01,...,8.815952e+02,4.042355e+02,1.454227e+03,2.076684e+04,8.139879e+01,8.836986e+02,4.047421e+02,1.458808e+03,4.170800e-01,4.571847e+00
min,3.826154e+00,-7.455341e+01,3.826154e+00,-7.455341e+01,0.000000e+00,0.000000e+00,-2.853500e+01,-1.000000e+00,-1.000000e-01,-2.000000e+00,...,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00
25%,4.605596e+00,-7.414732e+01,4.605672e+00,-7.414716e+01,0.000000e+00,0.000000e+00,3.297222e-01,7.098719e-01,6.861111e-02,0.000000e+00,...,2.264370e+02,1.397500e+02,2.719110e+02,6.574841e+03,4.156000e+00,2.264370e+02,1.397500e+02,2.719110e+02,0.000000e+00,2.627731e-01
50%,4.651627e+00,-7.410636e+01,4.651686e+00,-7.410626e+01,0.000000e+00,1.000000e+00,9.800000e-01,3.544358e+00,2.375000e-01,0.000000e+00,...,5.209980e+02,3.075350e+02,6.586700e+02,1.856499e+04,1.316900e+01,5.209980e+02,3.087880e+02,6.586700e+02,0.000000e+00,1.548207e+00
75%,4.713076e+00,-7.406990e+01,4.712982e+00,-7.406982e+01,1.000000e+00,1.000000e+00,2.674722e+00,1.107978e+01,7.416667e-01,1.000000e+00,...,8.698610e+02,5.390430e+02,1.188828e+03,3.258713e+04,3.311300e+01,8.724740e+02,5.390430e+02,1.188893e+03,0.000000e+00,5.126462e+00
max,5.283231e+00,-7.369859e+01,5.283231e+00,-7.369859e+01,1.000000e+00,1.000000e+00,6.730628e+02,2.310164e+02,1.437944e+01,4.000000e+00,...,7.864366e+03,6.263205e+03,1.288537e+04,3.346641e+05,7.931450e+02,7.864366e+03,6.263205e+03,1.288537e+04,1.000000e+00,7.799905e+01

In [62]:
pd.set_option('display.max_columns', None)
GPS_features_final

,OriginLat,OriginLon,DestinationLat,DestinationLon,Trip_Weekend,Trip_Weekday,Trip_TravelTime_Length_hour,RoadTime,duration (h),transfers,Origin_Home,Dest_Home,StartTime_Afternoon,StartTime_EveningPeak,StartTime_MorningOffPeak,StartTime_MorningPeak,StartTime_Night,EndTime_Afternoon,EndTime_EveningPeak,EndTime_MorningOffPeak,EndTime_MorningPeak,EndTime_Night,NSE_1 Alto,NSE_2 Medio-Alto,NSE_3 Medio,NSE_4 Medio-Bajo,NSE_5 Bajo,origin_taz,num_troncal_stops_perKM2_origin,num_alimentadores_stops_perKM2_origin,num_complementaria_stops_perKM2_origin,num_especial_stops_perKM2_origin,total_length_transit_km_perKM2_origin,dest_taz,num_troncal_stops_perKM2_dest,num_alimentadores_stops_perKM2_dest,num_complementaria_stops_perKM2_dest,num_especial_stops_perKM2_dest,total_length_transit_km_perKM2_dest,PopPerKM2_ZAT_Orig,Agro2018_perZAT_perKM2_orig,Com2018_perZAT_perKM2_orig,Ind2018_perZAT_perKM2_orig,Serv2018_perZAT_perKM2_orig,PopPerKM2_ZAT_Dest,Agro2018_perZAT_perKM2_dest,Com2018_perZAT_perKM2_dest,Ind2018_perZAT_perKM2_dest,Serv2018_perZAT_perKM2_dest,intra_zonal_trip,distance
0,4.741007,-74.106606,4.745094,-74.110470,0,1,0.307500,0.596086,0.177222,0,1,0,0,0,0,1,0,0,0,0,1,0,0.0,0.0,0.0,1.0,0.0,114,38.307054,0.0,0.0,0.0,19.943716,115,42.045283,0.0,0.0,0.0,26.223945,29485.705,7.183,482.562,300.338,558.379,80004.668,6.450,433.353,269.711,501.438,0,0.447317
1,4.740927,-74.106530,4.745082,-74.110466,0,1,3.062222,0.600653,0.179722,0,1,0,0,0,0,1,0,0,0,1,0,0,0.0,0.0,0.0,1.0,0.0,114,38.307054,0.0,0.0,0.0,19.943716,115,42.045283,0.0,0.0,0.0,26.223945,29485.705,7.183,482.562,300.338,558.379,80004.668,6.450,433.353,269.711,501.438,0,0.455580
2,4.740973,-74.106540,4.745284,-74.110520,0,1,5.836667,0.638595,0.190556,0,1,0,0,0,1,0,0,1,0,0,0,0,0.0,0.0,0.0,1.0,0.0,114,38.307054,0.0,0.0,0.0,19.943716,115,42.045283,0.0,0.0,0.0,26.223945,29485.705,7.183,482.562,300.338,558.379,80004.668,6.450,433.353,269.711,501.438,0,0.461606
3,4.740980,-74.106570,4.745112,-74.110520,0,1,4.756111,0.599897,0.178611,0,1,0,0,0,1,0,0,1,0,0,0,0,0.0,0.0,0.0,1.0,0.0,114,38.307054,0.0,0.0,0.0,19.943716,115,42.045283,0.0,0.0,0.0,26.223945,29485.705,7.183,482.562,300.338,558.379,80004.668,6.450,433.353,269.711,501.438,0,0.456885
4,4.740964,-74.106580,4.745061,-74.110480,0,1,0.834167,0.594913,0.176667,0,1,0,0,0,1,0,0,0,0,1,0,0,0.0,0.0,0.0,1.0,0.0,114,38.307054,0.0,0.0,0.0,19.943716,115,42.045283,0.0,0.0,0.0,26.223945,29485.705,7.183,482.562,300.338,558.379,80004.668,6.450,433.353,269.711,501.438,0,0.451252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699010,4.529459,-74.084370,4.530284,-74.081535,1,0,0.010000,0.279737,0.065556,0,1,0,0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,1.0,696,14.278676,0.0,0.0,0.0,7.698992,697,0.000000,0.0,0.0,0.0,0.000000,25221.371,1.360,131.908,113.096,148.453,0.000,2.353,424.780,300.444,467.140,0,0.316239
10699011,4.529420,-74.084530,4.530371,-74.081560,1,0,0.008333,0.269957,0.060556,0,1,0,0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,1.0,696,14.278676,0.0,0.0,0.0,7.698992,697,0.000000,0.0,0.0,0.0,0.000000,25221.371,1.360,131.908,113.096,148.453,0.000,2.353,424.780,300.444,467.140,0,0.331519
10699012,4.536099,-74.080520,4.531193,-74.080430,1,0,0.011667,1.191791,0.358333,0,1,0,1,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,0.0,1.0,698,9.272112,0.0,0.0,0.0,5.717046,697,0.000000,0.0,0.0,0.0,0.000000,33462.048,0.993,179.316,126.829,197.198,0.000,2.353,424.780,300.444,467.140,0,0.149967
10699013,4.525525,-74.087620,4.523111,-74.085420,1,0,0.025278,0.274268,0.112500,0,0,0,1,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,1.0,0.0,693,26.956816,0.0,0.0,0.0,11.463048,695,0.000000,0.0,0.0,0.0,2.244057,9075.357,0.749,72.634,62.275,81.744,0.000,10.535,1021.886,876.153,1150.060,0,0.255457
10699014,4.527107,-74.087074,4.524916,-74.086920,1,0,0.022778,0.269310,0.053611,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,696,14.278676,0.0,0.0,0.0,7.698992,695,0.000000,0.0,0.0,0.0,2.244057,25221.371,1.360,131.908,113.096,148.453,0.000,10.535,1021.886,876.153,1150.060,0,0.068963

In [63]:
GPS_features_final.to_csv('GPS_features_final.csv')